### ISSUE TITLE
Request failed with status code: 403

### ISSUE THREAD

**Issue by KrisshRp** [st1vms/unofficial-claude2-api#5] opened 2023-09-01 11:40 UTC
raise RuntimeError(f"Cannot retrieve Organization ID!\n{response.text}")
RuntimeError: Cannot retrieve Organization ID!
{"error": {"type": "permission_error", "message": "We are unable to serve your request"}}

**Comment by st1vms** [comment] 2023-09-01 15:13
Please refer to the TROUBLESHOOTING section, the reason you get this error is because of IP location restriction, try using a VPN connected to US/UK. Other locations may work sporadically or not work at all.

Closing this.

**Comment by XiaoXinYo** [comment] 2023-10-01 07:26
same，But my web works fine using VPN，And other methods of unofficial-claude2-api can also be used, except for send_ Message

**Comment by laserman2000** [comment] 2023-10-13 16:12
I have tested with a server located in the US and it's not working...I get the same error

**Comment by st1vms** [comment] 2023-11-14 12:02
Have you tried updating your session cookie from time to time? Also are you using the automatic session gathering with selenium, or the manual alternative?

**Comment by st1vms** [comment] 2023-11-14 18:50
> manual
> […](#)
> ------------------ Original ------------------ From: Stefano Raneri ***@***.***&gt; Date: Tue,Nov 14,2023 8:02 PM To: st1vms/unofficial-claude2-api ***@***.***&gt; Cc: Yang KaiQi ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [st1vms/unofficial-claude2-api] Request failed with status code:403 (Issue #5) Have you tried updating your session cookie from time to time? Also are you using the automatic session gathering with selenium, or the manual alternative? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Did you verified if cookie expired? You could give a shot to selenium auto session retrieval, also trying to run the example snippet to see if it works out...

**Comment by st1vms** [comment] 2023-12-05 13:54
@KrisshRp @XiaoXinYo @laserman2000 

Version 0.2.2 was released today, the 403 error seems to be fixed, also the library was updated to reflect new Claude 2.1 model!

Please let me know if this solves your issues...

**Comment by XiaoXinYo** [comment] 2023-12-08 12:52
now i get
`curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\xxy\Documents\123\venv\Lib\site-packages\curl_cffi\cacert.pem CApath: none'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.`

**Comment by st1vms** [comment] 2023-12-09 13:29
@XiaoXinYo It may be a conflicting version of `curl_cffi`.

Have you tried clean reinstalling the libraries? ( in both virtual env and system packages ).
So like issue these two commands in and outside the virtual env...

```shell
python -m pip uninstall unofficial-claude2-api curl_cffi
```

Then when you want to reinstall them, first upgrade `curl_cffi`:

```shell
python -m pip install --upgrade curl_cffi
```

Then reinstall this library:

```shell
python -m pip install unofficial-claude2-api
```

**Comment by XiaoXinYo** [comment] 2023-12-09 13:42
@st1vms I have reinstalled all the packages, but still reported an error, regardless of whether I am using VPN or not

**Comment by XiaoXinYo** [comment] 2023-12-09 13:44
@st1vms I manually get the cookies and ua
Python3.11
Windows11
Edge 120.0.2210.61

**Comment by st1vms** [comment] 2023-12-09 14:02
Looking at the libcurl error code reference page, this error seems to be: 
```txt
CURLE_SSL_CACERT_BADFILE (77)

Problem with reading the SSL CA cert (path? access rights?) 
```

Have you tried installing and running outside virtual environment?

**Comment by XiaoXinYo** [comment] 2023-12-09 14:13
@st1vms I don't think this is a problem caused by permissions (I have used administrator permissions)
In addition, there is an error in the import of example. It should be from claude2_api.xxx
![IMG_6659](https://github.com/st1vms/unofficial-claude2-api/assets/56395004/ce54a12b-a862-4de6-93b9-49750b882dc2)

**Comment by st1vms** [comment] 2023-12-09 14:32
Ok, thanks for spotting those typoos...

Have you tried the resolution steps I suggested before?

**Comment by XiaoXinYo** [comment] 2023-12-09 14:34
I'm ready to rest. I'll get back to you tomorrow.

**Comment by XiaoXinYo** [comment] 2023-12-10 05:46
I tried the method you gave me, but it still didn't work

**Comment by st1vms** [comment] 2023-12-10 13:48
`C:\Users\xxy\Documents\123\venv\Lib\site-packages\curl_cffi\cacert.pem`

This file should be included in the `curl_cffi` library folder in your virtual environment site-packages, please could you walk along the path directories taken from the path error returned trying to find `cacert.pem`?

**Comment by XiaoXinYo** [comment] 2023-12-10 15:06
Can be found
<img width="256" alt="微信图片_20231210230413" src="https://github.com/st1vms/unofficial-claude2-api/assets/56395004/d5e54126-1394-4ee4-bd14-77ae14fd0713">

**Comment by st1vms** [comment] 2023-12-11 14:21
Can you please try [these steps](https://snyk.io/blog/how-to-update-curl/) to update libcurl on Windows?

Please post the output of
```shell
curl --version
```

I would also suggest to delete and reinstall python3.11, when installing also do not check any box rather than "Add to PATH".

When installing python packages please do not use a virtual environment and also retain from using the Admin shell.

Thanks for your patience

**Comment by XiaoXinYo** [comment] 2023-12-12 05:42
Thank you, it was unexpectedly resolved

**Closed** 2023-12-12 12:41 UTC
